# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Laplace denstiy function
#' @description Laplace denstiy function using Rcpp
#' @param x variable vector
#' @return the density at \code{x}
#' @examples
#' \dontrun{
#' x <- seq(1, 3, length.out=10)
#' pdf <- d_lapalce(); pdf
#' }
#' @export
d_laplace <- function(x) {
    .Call('_StatComp20027_d_laplace', PACKAGE = 'StatComp20027', x)
}

#' @title Metropolis method
#' @description using Metropolis method implementing Mcmc
#' @param sigma vaiance
#' @param x0 initial values
#' @param N length
#' @return a list of \code{x} and iterator \code{k}
#' @examples
#' \dontrun{
#' sigma = 6.
#' x0 = 36.
#' N = 2000
#' model <- rw_Metropolis(sigma, x0, N)$x
#' plot(model)
#' }
#' @export
rw_Metropolis <- function(sigma, x0, N) {
    .Call('_StatComp20027_rw_Metropolis', PACKAGE = 'StatComp20027', sigma, x0, N)
}

